;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="GameplayCue.Aurora.Attack",DevComment="")
GameplayTagList=(Tag="GameplayCue.Aurora.Attack.Hit",DevComment="")
GameplayTagList=(Tag="GameplayCue.Aurora.FootStep",DevComment="")
GameplayTagList=(Tag="GameplayCue.Aurora.FootStepTest",DevComment="")
GameplayTagList=(Tag="GameplayCue.Aurora.Jump",DevComment="")
GameplayTagList=(Tag="GameplayCue.Aurora.Land",DevComment="")
GameplayTagList=(Tag="GameplayCue.Aurora.LevelStart",DevComment="")
GameplayTagList=(Tag="GameplayCue.Aurora.LevelStart.FBX",DevComment="")
GameplayTagList=(Tag="GameplayCue.Aurora.LevelStart.SFX",DevComment="")
GameplayTagList=(Tag="GameplayCue.Aurora.SkillE.Cast",DevComment="")
GameplayTagList=(Tag="GameplayCue.Aurora.SkillE.Hit",DevComment="")
GameplayTagList=(Tag="GameplayCue.Aurora.SkillE.Swing",DevComment="")
GameplayTagList=(Tag="GameplayCue.Aurora.SkillQ",DevComment="")
GameplayTagList=(Tag="GameplayCue.Aurora.SkillR.Cast",DevComment="")
GameplayTagList=(Tag="GameplayCue.Aurora.SkillR.Explosion",DevComment="")
GameplayTagList=(Tag="GameplayCue.Aurora.SkillR.Hit",DevComment="")

