;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagRedirects=(OldTagName="GameplayCue.LtBelica.Skill",NewTagName="GameplayCue.LtBelica.SkillE")
GameplayTagRedirects=(OldTagName="GameplayCue.LtBelica.Skill.Hit",NewTagName="GameplayCue.LtBelica.SkillE.Hit")
GameplayTagList=(Tag="GameplayCue.LtBelica.Attack.Hit",DevComment="")
GameplayTagList=(Tag="GameplayCue.LtBelica.SkillE",DevComment="")
GameplayTagList=(Tag="GameplayCue.LtBelica.SkillE.Dead",DevComment="")
GameplayTagList=(Tag="GameplayCue.LtBelica.SkillE.Hit",DevComment="")
GameplayTagList=(Tag="GameplayCue.LtBelica.SkillQ.Airborne",DevComment="")
GameplayTagList=(Tag="GameplayCue.LtBelica.SkillR.Camera",DevComment="")

