;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="AI.NPC.Minion.Melee",DevComment="근거리 미니언 태그")
GameplayTagList=(Tag="AI.NPC.Minion.Range",DevComment="원거리 미니언 태그")
GameplayTagList=(Tag="AI.NPC.Minion.Seige",DevComment="공성 미니언 태그")
GameplayTagList=(Tag="AI.NPC.Minion.Super",DevComment="슈퍼 미니언 태그")

GameplayTagList=(Tag="AI.NPC.Stat.Health",DevComment="Health 스탯 태그")
GameplayTagList=(Tag="AI.NPC.Stat.Attack",DevComment="Attack 스탯 태그")
GameplayTagList=(Tag="AI.NPC.Stat.Defense",DevComment="Defense 스탯 태그")
GameplayTagList=(Tag="AI.NPC.Stat.Speed",DevComment="Speed 스탯 태그")

GameplayTagList=(Tag="AI.NPC.State.Dead",DevComment="Npc 사망 태그")
GameplayTagList=(Tag="AI.NPC.State.Cooldown.Attack", DevComment="일반 공격 후 딜레이")

GameplayTagList=(Tag="Event.Montage.AttackHit", DevComment="근접 공격 타격 시점")
GameplayTagList=(Tag="Event.Montage.ProjectileFire", DevComment="원거리 발사 시점")

GameplayTagList=(Tag="Event.Ability.NPCBulletHit", DevComment="Npc 총알 Hit 이벤트")

GameplayTagList=(Tag="Event.Combat.CanAttack", DevComment="State Tree Combate State -> Attack State")
GameplayTagList=(Tag="Event.Combat.CanChase", DevComment="State Tree Combate State -> Chase State")

GameplayTagList=(Tag="Ability.Attack.Melee", DevComment="근접 공격 GA")
GameplayTagList=(Tag="Ability.Attack.Range", DevComment="원거리 공격 GA")
GameplayTagList=(Tag="Ability.Death", DevComment="사망 GA")

GameplayTagList=(Tag="GameplayCue.NPC.HitReact.Melee", DevComment="미니언 근거리 공격 피격 시 연출")
GameplayTagList=(Tag="GameplayCue.NPC.HitReact.Range", DevComment="미니언 원거리 공격피격 시 연출")